[features]
seeds = false
skip-lint = false
[programs.localnet]
chapter_one_reading_list = "2Nn7j2iepkGYBXaRgiq5fHvkqLS9rvMvSBNpGHBavHgu"
[programs.devnet]
chapter_one_reading_list = "2Nn7j2iepkGYBXaRgiq5fHvkqLS9rvMvSBNpGHBavHgu"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/jdunn/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
types = "app/src/idl/"
